version: '3.8'

services:
  # MongoDB service from the first compose
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env.docker

  # # App service from the first compose
  # jupyter-app:
  #   build: .
  #   volumes:
  #     - .:/workspace
  #   command: sleep infinity
  #   ports:
  #     - "8888:8888"



  # Postgres DB from the second compose
  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    env_file:
      - .env.docker


volumes:
  mongo-data:
  database_data:
    driver: local
